version: '3.9'
services:
  backend:
    image: aanchalgupta12/backend
    container_name: app-server
    ports:
      - 8080:8080
    networks:
      - app-network
    volumes:
      - app-data:/app
  frontend:
    image: aanchalgupta12/frontend
    container_name: web-server
    ports:
      - 80:80
    networks:
      - app-network
volumes:
  app-data: {}
networks:
  app-network:
    name: app-network
    driver: bridge